
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./vhost.d:/etc/nginx/vhost.d:ro"

  # portainer:
  #   image: portainer/portainer-ce:2.0.0
  #   command: -H unix:///var/run/docker.sock
  #   restart: always
  #   networks:
  #     - proxy
  #   environment:
  #     - VIRTUAL_HOST=portainer.direct2resort.com
  #     - VIRTUAL_PORT=9000
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

networks:
  default:
    name: ${test:-tmp}
    driver: bridge




# version: "3"
# services:
#   web:
#     image: iconkam/get-started:part2
#     deploy:
#       resources:
#         limits:
#           cpus: "0.1"
#           memory: 50M
#       restart_policy:
#         condition: on-failure
#     volumes:
#       - .:/app
#     ports:
#       - "80:80"
#     networks:
#       - webnet
# networks:
#   webnet:


# version: '3.6'
# services:
#   nginx-example:
#     image: nginx:latest
# web:
#     ports:
#       - "80:80"
# networks:
#   default:
#     name: ${test:-tmp}
#     driver: bridge



# version: "3"
# services:
#   web:
#     image: nginx:latest
#     deploy:
#       restart_policy:
#         condition: on-failure
#     volumes:
#       - .:/app
#     ports:
#       - "80:80"
# networks:
#   default:
#     name: ${test:-tmp}
#     driver: bridge